stages:
  - test

.test-common:
  stage: test
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    GRADLE_OPTIONS: --no-daemon --debug --stacktrace --warning-mode=all
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper
  artifacts:
    expire_in: 1 week
    paths:
      - build/distributions
      - build/libs

.test-linux:
  extends: .test-common
  before_script: &default_before_script_linux
    - curl -L https://nixos.org/nix/install | sh
    - chmod +x ./gradlew
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update

test:linux:
  extends: .test-linux
  image: eclipse-temurin:17
  before_script:
    - *default_before_script_linux
    - apt-get install --assume-yes build-essential fakeroot cmake xz-utils git
  script:
    - make btypes_primitives
    - git clone https://github.com/arximboldi/immer.git
    - cd immer
    - mkdir -p build && cd build
    - cmake .. && sudo make install & cd ..
    - mkdir cpp_build && cd cpp_build
    - cmake ..
    - make install & cd ..
    - ./gradlew test --stacktrace
