stages:
  - test

.test-common:
  stage: test
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    GRADLE_OPTIONS: --no-daemon --debug --stacktrace --warning-mode=all
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper
  artifacts:
    reports:
      junit:
        - "build/test-results/**/TEST-*.xml"

test:linux:
  image: eclipse-temurin:17
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update
    - apt-get install --assume-yes build-essential cmake git libboost-dev curl
    - curl -fsSL https://deb.nodesource.com/setup_21.x | bash -
    - apt-get install --assume-yes nodejs
    - npm install -g typescript
    - npm i --save-dev @types/node
  timeout: 3h
  script:
    - make btypes_primitives
    - git clone https://github.com/arximboldi/immer.git
    - cd immer
    - mv immer /usr/local/include/
    - cd ..
    - mkdir cpp_build && cd cpp_build
    - cmake ..
    - make install & cd ..
    - ./gradlew test --stacktrace
