stages:
  - build
  - test

.test-common:
  stage: test
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper
  artifacts:
    expire_in: 1 week
    paths:
      - build/distributions
      - build/libs

.test-linux:
  extends: .test-common
  before_script: &default_before_script_linux
    - chmod +x ./gradlew
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update

test:linux:
  extends: .test-linux
  image: eclipse-temurin:17
  before_script:
    - *default_before_script_linux
    - apt-get install --assume-yes build-essential fakeroot
  script:
    - ./gradlew test
