[package]
name = "btypes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
im = "15.0.0"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
num-traits = "0.2.14"
num-iter = "0.1.42"